pref("extensions.proxtube.intpref_status", 1);
pref("extensions.proxtube.intpref_firststart", 1);
pref("extensions.proxtube.boolpref_agreementaccepted", false);
pref("extensions.proxtube.boolpref_shownotf", false);
pref("extensions.proxtube.boolpref_showsslnotf", false);
pref("extensions.proxtube.intpref_enabled", 0);
pref("extensions.proxtube.intpref_http", 0);
pref("extensions.proxtube.stringpref_http", "");
pref("extensions.proxtube.boolpref_showfoxydeal", false);